Wordpress
DMiTRONiK/DevOps-experience pull request #1
Opened 2022-04-18 09:24 UTC by DMiTRONiK

### [hello_world](https://github.com/DMiTRONiK/DevOps-experience/tree/wordpress/hello_world)
Пример создания простого Dockerfile 
### [WorldPress](https://github.com/DMiTRONiK/DevOps-experience/tree/wordpress/wordpress)
Пример создания сложного Dockerfile с установкой дополнительных пакетов и копированием файлов внутрь контейнера.

2022-04-18 09:26 UTC, ctrlok commented
Какие файлы ты сам написал, а что скопипастил?

2022-04-18 09:29 UTC, ctrlok commented on hello_world/index.php
> +<?php
зачем нужна эта строка?

2022-04-18 09:33 UTC, DMiTRONiK commented on hello_world/index.php
> +<?php
объявление блока php для интерпретатора, чтобы он знал как обрабатывать дальнейшие команды

2022-04-18 09:39 UTC, DMiTRONiK commented on hello_world/index.php
> +<?php
> Какие файлы ты сам написал, а что скопипастил?

[Dockerfile](https://github.com/DMiTRONiK/DevOps-experience/blob/wordpress/wordpress/Dockerfile) - сам писал, 
[docker-entrypoint.sh](https://github.com/DMiTRONiK/DevOps-experience/blob/wordpress/wordpress/docker-entrypoint.sh) - скопировал, но что он делает понимаю. Можно было его упростить с учетом, что у меня только апач и нет необходимости определять на чем запущенно, а можно сразу назначать правильного владельца для файлов. 
[wp-config-docker.php](https://github.com/DMiTRONiK/DevOps-experience/blob/wordpress/wordpress/wp-config-docker.php) - скопировал тоже

2022-04-18 09:42 UTC, ctrlok requested changes
Добавь комментарии по файлам, особенно по тем что не написал сам. Что делает каждая строка? Если не понимаешь причины зачем сделано — перепиши так чтобы понимать что и зачем происходит.

2022-04-18 09:42 UTC, ctrlok commented on wordpress/.htaccess
> +RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
Что означает эта строка? Добавь комментарий

2022-04-18 09:42 UTC, ctrlok commented on wordpress/.htaccess
> +RewriteRule ^index\.php$ - [L]
что означает эта строка и строки ниже? Добавь комментарии

2022-04-18 09:42 UTC, ctrlok commented on wordpress/Dockerfile
> +RUN set -ex; \
Зачем тут нужен set -ex и почему он не был использован в предыдущем ране?

2022-04-18 09:42 UTC, ctrlok commented on wordpress/Dockerfile
> +	apt-get update; \
зачем дважды проводить `apt-get update`?

2022-04-18 09:42 UTC, ctrlok commented on wordpress/Dockerfile
> +	pecl install imagick-3.6.0; \
Какая причина того что это всё сделано одной большой строкой?

2022-04-18 09:58 UTC, DMiTRONiK commented on wordpress/Dockerfile
> +RUN set -ex; \
-e - останавливает выполнение при возникновении ошибки 
-х - используется для отладки, выводит каждую запущенную команду
На предыдущем шаге нет необходимости в сборке пакетов и не нужно проверять на ошибки

2022-04-18 10:06 UTC, DMiTRONiK commented on wordpress/Dockerfile
> +	pecl install imagick-3.6.0; \
Для уменьшения количества уровней в докерфайле и уменьшении итогового размера образа, стараются сделать максимум за одну инструкцию RUN

2022-04-18 10:13 UTC, DMiTRONiK commented on wordpress/Dockerfile
> +	apt-get update; \
На предыдущем шаге мы очистили список пакетов rm -rf /var/lib/apt/lists/* 
дабы в дальнейшем избежать проблем с закэшированными инструкциями

2022-04-18 10:31 UTC, ctrlok commented on wordpress/Dockerfile
> +	apt-get update; \
каких проблем?

2022-04-18 12:23 UTC, ctrlok commented on wordpress/Dockerfile
> +	pecl install imagick-3.6.0; \
можно ли разделить на несколько разных команд без того чтобы сильно увеличить размер? попробуй разделить так чтобы не было большой разницы в размере

2022-04-18 12:24 UTC, ctrlok commented on wordpress/Dockerfile
> +RUN set -ex; \
можно ли заменить `-e` на `&&` и в чём будет разница?

2022-04-18 14:13 UTC, DMiTRONiK commented on wordpress/.htaccess
> +RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
Обновил, добавил комментарии

2022-04-18 14:13 UTC, DMiTRONiK commented on wordpress/.htaccess
> +RewriteRule ^index\.php$ - [L]
Обновил

2022-04-18 14:45 UTC, DMiTRONiK commented on wordpress/Dockerfile
> +RUN set -ex; \
> можно ли заменить `-e` на `&&` и в чём будет разница?

можно заменить, не найду точного ответа, возможно зависит от типа шелла в изначальном образе

2022-04-18 14:57 UTC, DMiTRONiK commented on wordpress/Dockerfile
> +	pecl install imagick-3.6.0; \
> можно ли разделить на несколько разных команд без того чтобы сильно увеличить размер?
Можно, если команда не подразумевает удаление или изменение файлов с предыдущего шага, то такое разделение не должно сказываться на итоговом размере. Любое изменение файла с предыдущего слоя не удаляет его физически в готовом образе, а только отмечает недоступным на текущем слое.

2022-04-18 15:01 UTC, DMiTRONiK commented on wordpress/Dockerfile
> +	apt-get update; \
> каких проблем?

При внесении изменений в существующий Dockerfile при сборке образа будет пересобрана только та инструкция RUN в которую вносились правки, в связи с этим команды update и install всегда выполняют за одну инструкцию.

2022-04-19 09:39 UTC, ctrlok approved these changes

2022-04-19 10:01 UTC, merged